apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: frontend
        image: turbosaurio/frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        command: [ "echo", "SUCCESS" ]

---

apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 31000
  selector:
    app: udagram-frontend
  type: LoadBalancer