apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-frontend
  template:
    metadata:
      labels:
        app: udagram-frontend
    spec:
      containers:
      - name: frontend
        image: turbosaurio/frontend
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
spec:
  ports:
  - port: 4200
    targetPort: 80
    protocol: TCP
  selector:
    run: udagram-frontend
  type: LoadBalance